export const SET_CONSTRUCTOR_INGREDIENT = "SET_CONSTRUCTOR_INGREDIENT";
export const SET_CONSTRUCTOR_BUN = "SET_CONSTRUCTOR_BUN";
export const UPDATE_CONSTRUCOR_IGREDIENTS_DATA = "UPDATE_CONSTRUCOR_IGREDIENTS_DATA";
export const REPLACE_CONSTRUCTOR_ITEM = "REPLACE_CONSTRUCTOR_ITEM";
export const DELETE_CONSTRUCTOR_INGREDIENT = "DELETE_CONSTRUCTOR_INGREDIENT";